/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab8;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Lab6__dv extends javax.swing.JFrame {

    static ArrayList<Seresv> sv = new ArrayList();

    /**
     * Creates new form Lab6__dv
     */
    public Lab6__dv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        Agregar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_servivio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jb_agregaruni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb_humano = new javax.swing.JRadioButton();
        rb_amanto = new javax.swing.JRadioButton();
        sp_poder = new javax.swing.JSpinner();
        sp_años = new javax.swing.JSpinner();
        tf_nombre = new javax.swing.JTextField();
        tf_planeta = new javax.swing.JTextField();
        jb_agregarsv = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_serv = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cb_modsv = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cb_elimsv = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jb_elimsv = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_cargar = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agregar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AgregarStateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agregar Ser vivo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 13, -1, -1));

        jLabel2.setText("Agregar Universo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        cb_servivio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_servivioItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_servivio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 126, -1));

        jLabel4.setText("Agregar ser vivo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        jb_agregaruni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/good.png"))); // NOI18N
        jb_agregaruni.setText("Agregar universo");
        jb_agregaruni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregaruniMouseClicked(evt);
            }
        });
        jPanel1.add(jb_agregaruni, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, -1, -1));

        jLabel6.setText("Poder:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, -1, -1));

        jLabel7.setText("Años:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, -1, -1));

        jLabel8.setText("Planeta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 228, -1, -1));

        jLabel9.setText("Raza:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, -1, -1));

        rb_humano.setText("Humano");
        jPanel1.add(rb_humano, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 280, -1, -1));

        rb_amanto.setText("Amantò");
        jPanel1.add(rb_amanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 280, -1, -1));
        jPanel1.add(sp_poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(sp_años, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 159, -1, -1));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 42, 110, -1));
        jPanel1.add(tf_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 225, 114, -1));

        jb_agregarsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/check.png"))); // NOI18N
        jb_agregarsv.setText("Agregar ser vivo");
        jb_agregarsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarsvMouseClicked(evt);
            }
        });
        jPanel1.add(jb_agregarsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 332, -1, -1));

        jt_serv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Poder", "Años", "Planeta", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_serv);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 381, 198));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/administrator.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 476));

        Agregar.addTab("Agregar", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Modificar Ser vivo");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/admin-ui (1).png"))); // NOI18N
        jButton1.setText("Nombre");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/calendar.png"))); // NOI18N
        jButton2.setText("Años");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/region.png"))); // NOI18N
        jButton3.setText("Planeta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/feedback.png"))); // NOI18N
        jButton4.setText("Raza");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/reading-glasses.png"))); // NOI18N
        jButton5.setText("Poder");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 110, 40));

        jPanel3.add(cb_modsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 195, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/dispositivos.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -20, -1, -1));

        Agregar.addTab("Modificar", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.add(cb_elimsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 157, -1));

        jLabel10.setText("Eliminar Ser vivo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        jb_elimsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/forbidden.png"))); // NOI18N
        jb_elimsv.setText("Eliminar");
        jb_elimsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elimsvMouseClicked(evt);
            }
        });
        jPanel2.add(jb_elimsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/remove.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -20, -1, -1));

        Agregar.addTab("Eliminar", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/ojo.png"))); // NOI18N
        jButton6.setText("Cargar Archivo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        ta_cargar.setColumns(20);
        ta_cargar.setRows(5);
        jScrollPane2.setViewportView(ta_cargar);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 430, 250));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab8/Imagenes/pencil.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        Agregar.addTab("Cargar Archivo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Agregar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarsvMouseClicked
        // TODO add your handling code here:

        if (((int) sp_poder.getValue() >= 1) && ((int) sp_poder.getValue() <= 10)) {
            String nombre, planeta, raza;
            int años, poder;
            raza = "";
            nombre = tf_nombre.getText();
            planeta = tf_planeta.getText();
            if (rb_humano.isSelected()) {
                raza = "Humano";
            } else if (rb_amanto.isSelected()) {
                raza = "Amantó";
            }
            años = (int) sp_años.getValue();
            poder = (int) sp_poder.getValue();
            Seresv v = new Seresv(nombre, poder, años, planeta, raza);
            sv.add(v);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_servivio.getModel();
            modelo.addElement(v);
            cb_servivio.setModel(modelo);
            sp_poder.setValue(0);
            sp_años.setValue(0);
            tf_nombre.setText("");
            tf_planeta.setText("");
            rb_amanto.setSelected(false);
            rb_humano.setSelected(false);
            JOptionPane.showMessageDialog(null, "Agregado con exito");
        } else {
            JOptionPane.showMessageDialog(null, "Su poder es inferior o superior a lo que nosotros manejamos");
        }
    }//GEN-LAST:event_jb_agregarsvMouseClicked

    private void jb_agregaruniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregaruniMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        int seleccion = jfc.showSaveDialog(this);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                universo = new File(jfc.getSelectedFile().getPath() + ".txt");
                fw = new FileWriter(universo);
                bw = new BufferedWriter(fw);

                DefaultTableModel modelo = (DefaultTableModel) jt_serv.getModel();
                String acum = "";
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    for (int j = 0; j < modelo.getColumnCount(); j++) {
                        acum += modelo.getValueAt(i, j) + ";";
                    } // Fin For
                    acum += "\n";
                } // Fin For
                bw.write(acum);
                bw.flush();
                JOptionPane.showMessageDialog(this, "¡Se ha guardado exitosamente el nuevo archivo!");
            } catch (Exception e) {
                e.printStackTrace();
            } // Fin Try Catch
            try {
                bw.close();
                fw.close();
            } catch (IOException io) {
                io.printStackTrace();
            } // Fin Try Catch
        }
    }//GEN-LAST:event_jb_agregaruniMouseClicked

    private void AgregarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AgregarStateChanged
        // TODO add your handling code here:
        try {

            if (Agregar.getSelectedIndex() == 2) {
                Universo p = new Universo(universo.getPath());
                p.cargarArchivo();
                DefaultComboBoxModel model = new DefaultComboBoxModel(p.getVivos().toArray());
                cb_elimsv.setModel(model);
            } else if (Agregar.getSelectedIndex() == 1) {
                Universo p = new Universo(universo.getPath());
                p.cargarArchivo();
                DefaultComboBoxModel model = new DefaultComboBoxModel(p.getVivos().toArray());
                cb_modsv.setModel(model);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AgregarStateChanged

    private void jb_elimsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elimsvMouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            p.Eliminar(((Seresv) cb_elimsv.getSelectedItem()).getNombre());
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_elimsv.getModel();
            model.removeElement(cb_elimsv.getSelectedItem());
            cb_elimsv.setModel(model);
            JOptionPane.showMessageDialog(null, "Se elimino con exito");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_elimsvMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            String nombre = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre porfavor");
            Seresv v = (Seresv) cb_modsv.getSelectedItem();
            p.Modnombre(v.getNombre(), nombre);
            v.setNombre(nombre);

            JOptionPane.showMessageDialog(null, "Se modifico con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            int años = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese la nueva edad porfavor"));
            Seresv v = (Seresv) cb_modsv.getSelectedItem();
            p.Modaños(v.getNombre(), años);
            v.setAños(años);
            JOptionPane.showMessageDialog(null, "Se modifico con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            int poder = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el neuvo poder porfavor"));
            if ((poder >= 1) && (poder <= 10)) {
                Seresv v = (Seresv) cb_modsv.getSelectedItem();
                p.Modpoder(v.getNombre(), poder);
                v.setPoder(poder);
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
            } else {
                JOptionPane.showMessageDialog(null, "Su poder es inferior o superior a lo que nosotros manejamos");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            String planeta = JOptionPane.showInputDialog(null, "Ingrese el nuevo planeta porfavor");
            Seresv v = (Seresv) cb_modsv.getSelectedItem();
            p.Modplaneta(v.getNombre(), planeta);
            v.setPlaneta(planeta);
            JOptionPane.showMessageDialog(null, "Se modifico con exito");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {
            Universo p = new Universo(universo.getPath());
            p.cargarArchivo();
            String raza = JOptionPane.showInputDialog(null, "Ingrese el nuevo planeta porfavor(Humano o Amanto)");
            if (raza.equals("Humano") || raza.equals("Amanto")) {
                Seresv v = (Seresv) cb_modsv.getSelectedItem();
                p.Modraza(v.getNombre(), raza);
                v.setRaza(raza);
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar debido a que su tipo de raza no existe");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_servivioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_servivioItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            Seresv s = (Seresv) cb_servivio.getSelectedItem();
            Object[] newrow = {
                s.getNombre(), s.getPoder(), s.getAños(), s.getPlaneta(), s.getRaza()
            };

            DefaultTableModel modelo = (DefaultTableModel) jt_serv.getModel();
            modelo.addRow(newrow);
            jt_serv.setModel(modelo);

        }
    }//GEN-LAST:event_cb_servivioItemStateChanged

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        ta_cargar.setText("");
        try {
            JFileChooser filechooser = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
            filechooser.setFileFilter(filtro);
            int seleccion = filechooser.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                universo=filechooser.getSelectedFile();
                fichero = filechooser.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                ta_cargar.setText("");
                while ((linea = br.readLine()) != null) {
                    ta_cargar.append(linea);
                    ta_cargar.append("\n");
                } // Fin While
            } // Fin If 
        } catch (Exception e) {
            e.printStackTrace();
        } // Fin Try Catch
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        } // Fin Try Catch
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6__dv.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6__dv.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6__dv.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6__dv.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6__dv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Agregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_elimsv;
    private javax.swing.JComboBox<String> cb_modsv;
    private javax.swing.JComboBox<String> cb_servivio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregarsv;
    private javax.swing.JButton jb_agregaruni;
    private javax.swing.JButton jb_elimsv;
    private javax.swing.JTable jt_serv;
    private javax.swing.JRadioButton rb_amanto;
    private javax.swing.JRadioButton rb_humano;
    private javax.swing.JSpinner sp_años;
    private javax.swing.JSpinner sp_poder;
    private javax.swing.JTextArea ta_cargar;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_planeta;
    // End of variables declaration//GEN-END:variables
File universo;
}
